name: sr_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - matplotlib
  - scipy
  - pip
  - pip:
    - flax
    - datasets
    - transformers[torch]
    - wandb
    - tqdm
    - numexpr
    - scikit-learn
    - trl